name: Lint and Test

on: [push, pull_request]

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - name: install
              run: yarn install --frozen-lockfile
            - name: test
              run: yarn test
